import Navbar from '@/components/Navbar/Navbar'
import '../styles/globals.css'
import { Inter } from 'next/font/google'
import Wpp from '@/components/Wpp/Wpp'
import Footer from '@/components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Ecommerce',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='es'>
			<body className={inter.className}>
				<Navbar />
				{children}
				<Wpp />
				<Footer />
			</body>
		</html>
	)
}
